import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "../components/Footer";
import SessionWrapper from "@/components/SessionWrapper";

export const metadata: Metadata = {
  title: "Adopt-a-Pal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }:
  Readonly<{ children: React.ReactNode }>) {

  return (
    <SessionWrapper>
      <html lang="en">
        <body>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </SessionWrapper>
  );
}
